title: Yu-Chieh Jack Ho
logo: /assets/img/profile_j.png
description: Welcome!
intro: A data scientist / AI researcher with end-to-end product development experiences
show_links: true

plugins:
  - jekyll-seo-tag
