title: Yu-Chieh Jack Ho
#logo: /assets/img/profile_j.jpg
description: Welcome!
intro: I am a data scientist with solid research skills and end-to-end product development experiences.
show_links: true

plugins:
  - jekyll-seo-tag
